# Site settings
title: Introduction to survival analysis
# description and keywords for meta tags
description: "A very brief workshop on NICE DSU TSDs on survival analysis!"
keywords: "workshops, survival-analysis"

# author settings for cc-by
author: Mohamamdreza Amiri
pub_year: 2024
github_username: rexaamiri
twitter_username: rexaamiri

# add the full url for the github repository
repo: "https://github.com/rexaamiri/rexaamiri.github.io"

# site urls
# add the url for the domain,
# on gh-pages: https://username.github.io 
url: https://rexaamiri.github.io
# add subsection of the domain,
# on gh-pages this is the name of the repository
baseurl: /content/0-prep.html

# add search box to top nav
search: true

# add google analytics if desired (optional)
# if blank, it will be ignored
# use JEKYLL_ENV=production on build command
google_analytics: 

# defaults (to simplify front matter)
collections:
  sections:
    output: true
defaults:
  - scope:
      path: ""
      type: "sections"
    values:
      layout: "section"

# text column settings 
text-col-size: 8 

# Build settings
markdown: kramdown
